vmap  <expr>  <LEFT>   dragvisual#DVB_Drag('left')                        
vmap  <expr>  <RIGHT>  dragvisual#DVB_Drag('right')                      
vmap  <expr>  <DOWN>   dragvisual#DVB_Drag('down')                        
vmap  <expr>  <UP>     dragvisual#DVB_Drag('up')                         
vmap  <expr>  D        dragvisual#DVB_Duplicate()                          
