source ~/.vim/bundle/vim-prompt/prompt.vim
source ~/.vim/bundle/vim-wordsubstitute/wordsubstitute.vim
source ~/.vim/bundle/vim-quickman/quickman.vim
source ~/.vim/bundle/vim-quote/quote.vim
source ~/.vim/bundle/vim-smartfold/smartfold.vim
source ~/.vim/bundle/vim-misc/vmisc.vim
source ~/.vim/bundle/vim-clearhi/ClearHi.vim
source ~/.vim/bundle/vim-smartinsert/smartinsert.vim
source ~/.vim/bundle/vim-slashsearch/slashsearch.vim
source ~/.vim/bundle/vim-alignchar/alignchar.vim
source ~/.vim/bundle/vim-center/goto_center.vim
source ~/.vim/bundle/vim-moveblock/moveblock.vim
source ~/.vim/bundle/vim-morespaces/morespaces.vim
