" The syntax file...

" define highlight group...
		highlight FunctionalOperator term=reverse ctermfg=LightCyan ctermbg=NONE 

" define syntax rule...
syntax match FunctionalOperator /\(->\)\|→\|:\|∈\|%\|@\|\^\|\(\~>\)/
syntax region  FunctionalOperator start="<" end=">"

" others...
" if hlID("FunctionalOperator") == 0
"		highlight clear FunctionalOperator
