# Source bash config ...
alias sb="source ~/.bash_profile"
alias sbvi="vi ~/.bash_profile"

# Manage $PATH ... 
export PATH="/opt/local/bin:$PATH"

# Add bash functions ...
source ~/.vim/rc/bash_functions.sh

# Add bash alias ...
source ~/.vim/rc/bash_alias.sh

# Add directory shotcuts ...
source ~/.vim/rc/quick_directories

# Python executable path ...
source ~/.vim/rc/bash_executable.sh

# Add env for apps ...
source ~/.vim/rc/bash_env.sh
