# ============================================================================
# Python executable path ...
# ============================================================================

# Python path...
export PYTHONPATH=""
export PYTHONPATH="$HOME/Dropbox/codes:$PYTHONPATH"
export PYTHONPATH="$HOME/.local/lib64/python3.8/site-packages/:$PYTHONPATH"

# PDF split ...
export PATH="$HOME/Dropbox/utilities/pdf_utility:$PATH"

# inSituX -- serial crystallography software ...
export PATH="$HOME/Dropbox/codes/inSituX:$PATH"

# pme for pandoc, markdown and entr...
export PATH="$HOME/Dropbox/codes/pme:$PATH"

# texpro for LaTeX...
export PATH="$HOME/Dropbox/codes/texpro:$PATH"

# time difference in days...
export PATH="$HOME/Dropbox/codes/deltat:$PATH"

# pdf2txt, word count...
export PATH="$HOME/Dropbox/codes/wordcount:$PATH"
