# ============================================================================
# Python executable path ...
# ============================================================================

# Set a lib path for Python to look for its modules ...
export PYTHONPATH="$HOME/Dropbox/Projects:$PYTHONPATH"

# Concept library ...
export PATH="$HOME/Dropbox/Projects/DefineConcepts:$PATH"

# Word library ...
export PATH="$HOME/Dropbox/Projects/DefineWords:$PATH"

# PDF split ...
export PATH="$HOME/Dropbox/Projects/PDF.Utility:$PATH"
