# ============================================================================
# Python executable path ...
# ============================================================================

# Python path...
export PYTHONPATH=""
export PYTHONPATH="$HOME/Dropbox/codes:$PYTHONPATH"

# PDF split ...
export PATH="$HOME/Dropbox/utilities/pdf_utility:$PATH"

# inSituX.Ctrl -- serial crystallography software ...
export PATH="$HOME/Dropbox/codes/inSituX/ctrl:$PATH"

# inSituX -- serial crystallography software ...
export PATH="$HOME/Dropbox/codes/inSituX:$PATH"

# FTP server -- serial crystallography software ...
export PATH="$HOME/Dropbox/codes/FTP.server:$PATH"
export PATH="$HOME/Dropbox/codes/FTP.server/Client:$PATH"

# pme for pandoc, markdown and entr...
export PATH="$HOME/Dropbox/codes/pme:$PATH"

# texpro for LaTeX...
export PATH="$HOME/Dropbox/codes/texpro:$PATH"
