# Set neovim as vi ...
alias vi="nvim "

# Typos ...
alias sl="ls "

# Shorter grep ...
alias gp="grep --color -e "
alias gpi="grep --color -i -e "
alias gpiv="grep --color -iv -e "

# Apply function on each item filtered by xargs ...
alias sargs="xargs -I it -n 1 "

# Easier ls ...
alias lst="ls -lrt "
