function claude.setup {
    local VERSIONS_DIR="$HOME/.local/share/claude/versions"
    local TARGET="$HOME/.local/bin/claude"
    local MARKER="# AUTO-GENERATED by claude.setup"

    # Check if versions directory exists and has binaries
    if [ ! -d "$VERSIONS_DIR" ] || [ -z "$(ls "$VERSIONS_DIR" 2>/dev/null)" ]; then
        echo "claude.setup: No binaries found in $VERSIONS_DIR, skipping." >&2
        return 1
    fi

    # If wrapper already exists with the marker, skip
    if [ -f "$TARGET" ] && grep -q "$MARKER" "$TARGET" 2>/dev/null; then
        return 0
    fi

    # Ensure ~/.local/bin exists
    mkdir -p "$HOME/.local/bin"

    # Remove existing file/symlink if present
    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        rm -f "$TARGET"
    fi

    # Write the wrapper script
    cat > "$TARGET" << 'WRAPPER'
#!/bin/bash
# AUTO-GENERATED by claude.setup
VERSIONS_DIR="$HOME/.local/share/claude/versions"
LATEST="$(ls "$VERSIONS_DIR" 2>/dev/null | sort -V | tail -1)"
if [ -z "$LATEST" ]; then
    echo "Error: No claude binary found in $VERSIONS_DIR" >&2
    exit 1
fi
exec "$VERSIONS_DIR/$LATEST" "$@"
WRAPPER

    chmod +x "$TARGET"
    ## echo "claude.setup: Created wrapper at $TARGET"
}
claude.setup
